[general]
version = "0.2.0"

[problem]
problem_name = "ahc048"
objective = "Min"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer"

# ==============================
#         COMPILE STEPS
# ==============================

# Compile the user's program
[[test.compile_steps]]
program = "clang++"
args = [
  "-std=c++20",
  "-Wall",
  "-Wextra",
  "-O2",
  "-DONLINE_JUDGE",
  "-DATCODER",
  "-mtune=native",
  "-march=native",
  "-fconstexpr-depth=2147483647",
  "-fconstexpr-steps=2147483647",
  "-I/opt/boost/clang/include",
  "-L/opt/boost/clang/lib",
  "-I/opt/ac-library",
  "-I/usr/include/eigen3",
  "-I/home/kosuke/lib/cpp-dump",
  "-I/home/kosuke/lib/ac-library-master",
  "main.cpp",
]


# ==============================
#           TEST STEPS
# ==============================

# Run the user's program
[[test.test_steps]]
program = "./a.out"
args = []
stdin = "./tools/in/{SEED04}.txt"
stdout = "./tools/out/{SEED04}.txt"
stderr = "./tools/err/{SEED04}.txt"
measure_time = true

# Run the visualizer to calculate the score
[[test.test_steps]]
program = "cargo"
args = [
    "run",
    "--bin",
    "vis",
    "--release",
    "./in/{SEED04}.txt",
    "./out/{SEED04}.txt",
]
current_dir = "./tools"
measure_time = false
